### ISSUE TITLE
TypeError: Promise.defer is not a function

### ISSUE THREAD

**Issue by leroydev** [dial-once/node-bunnymq#52]
When using Node.js V7.0 and calling `.produce`, I get the following error:

```
bmq:producer TypeError: Promise.defer is not a function
    at createRpcQueue.call.then (C:\project\node_modules\bunnymq\src\modules\producer.js:121:43)
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

**Comment by PuKoren** [comment]
Ok, they must have removed the support of deferred promises as it was already deprecated. Thanks for the report, we will have to fix this

**Comment by PuKoren** [comment]
@leroydev: can you give a check with the latest version (2.2.2) and confirm your issue is fixed with node 7?

**Comment by leroydev** [comment]
@PuKoren No errors anymore on Node.js V7.0.0, thanks for the fix! 👍
