### ISSUE TITLE
Document RPC timeout usage

### ISSUE THREAD

**Issue by leroydev** [dial-once/node-bunnymq#53]
Maybe I'm misunderstanding how it should work, but when a producer produces a RPC message and no consumer consumes it, the producer will just keep waiting for an answer which will never come. 

I'd expect the producer to at some point give up and return an error.

Code:
```
var bunnyMQ = require('bunnymq');
var producer = bunnyMQ({
  host: 'amqp://username:password@localhost:5672',
  timeout: 100,
  transport: {
    info: console.log,
    debug: console.log,
    log: console.log,
    warn: console.log,
    error: console.log
  }
}).producer;

producer.produce('fnCall', {}, {rpc: true}).then(function() {
  console.log('Response received');
}).catch(function(err) {
  console.log(err);
});
```

This gives the following output in the console:
```bmq:producer [fnCall] >  {}```

bunnymq version: 2.2.1
Node.js version: 6.9.1

**Comment by PuKoren** [comment]
Hello!

You have to use timeout in the producer options, like so:

``` js
producer.produce('fnCall', {}, {rpc: true, timeout: 100}).then(function() {
  console.log('Response received');
}).catch(function(err) {
  console.log(err);
});
```

Global timeout is for connection timeout to the broker only - we lack a bit of documentation on this one!

**Comment by leroydev** [comment]
@PuKoren That indeed works as expected! Thanks for the speedy response! :)

**Comment by PuKoren** [comment]
Cool! I'll change the issue to request more doc, thanks for the heads up

**Comment by shamil** [comment]
I've hit into this as well, the `timeout` param only works once you have connection to the broker. For example, If rabbitmq is down the `timeout` never fire
