### ISSUE TITLE
Refactor and use ES6 syntax throughout the project

### ISSUE THREAD

**Issue by mrister** [dial-once/node-bunnymq#57]
As a result of this conversation:
https://github.com/dial-once/node-bunnymq/pull/54

We decided it would be good to refactor the project to es6 the goals aside from syntax change are:
- Remove usage of global vars where possible
- Limit the scope of variables where possible
- Do not use deferred mechanism but native Promises
- Es lint clean code
- No arrow function and this (where possible to avoid)
- Latest Node version compliant

**Comment by Spring3** [comment]
Changes provided in #75
