### ISSUE TITLE
Add fallback for LOCAL_QUEUE

### ISSUE THREAD

**Issue by ykhatal** [dial-once/node-bunnymq#71]
We should make the `LOCAL_QUEUE` env var optional and add a fallback when it's undefined, or it will be undefined and produce queues like `queue:nameundefined` and this put the service out of usage

**Comment by mrister** [comment]
wo! nice catch and take a look at this:
![image](https://cloud.githubusercontent.com/assets/1213258/22336619/21f02b4a-e3e3-11e6-9344-1f45d474e8b1.png)

**Comment by ykhatal** [comment]
@mrister :laughing: I was looking for a way to remove them but not one by one.
If you click to the right `+` and add consumers cout, you will notice that there is no consumer on those queues, since i redeployed the `service-device` and set the `LOCAL_QUEUE`.

**Comment by mrister** [comment]
Yeah those queues should not be durable as they would have been removed.
