### ISSUE TITLE
Tests failing due to Docker

### ISSUE THREAD

**Issue by Spring3** [dial-once/node-bunnymq#78]
When running tests on CircleCI, it fails to remove the docker image:
``Error: Command failed: docker rm -f rabbitmq-bunnymq``

**Comment by leroydev** [comment]
The complete error that's happening in CircleCI:
```
Error: Command failed: docker rm -f rabbitmq-bunnymq
Error response from daemon: Driver btrfs failed to remove root filesystem a2d43d27709751563ccf3ebef5da34404306104cf0da963159301adcfe2abf0a: Failed to destroy btrfs snapshot /var/lib/docker/btrfs/subvolumes for a2d43d27709751563ccf3ebef5da34404306104cf0da963159301adcfe2abf0a: operation not permitted
Error: failed to remove containers: [rabbitmq-bunnymq]
```

An explanation and (dirty) fix for this error are given here https://circleci.com/docs/1.0/docker-btrfs-error/.
CircleCI forum thread about this: https://discuss.circleci.com/t/docker-error-removing-intermediate-container/70.

**Comment by Spring3** [comment]
@leroydev thanks for the update
