### ISSUE TITLE
Error is lost during in the outgoing message

### ISSUE THREAD

**Issue by Spring3** [dial-once/node-bunnymq#83]
The problem lies [here](
https://github.com/dial-once/node-bunnymq/blob/develop/src/modules/message-parsers.js#L29)
The reason for that is because JSON.stringify(error) results in an empty object.

Suggested solution is to use [this module](https://www.npmjs.com/package/deserialize-error)

Test case
```js
// inside a consumer handler
.catch((error) => {
  return { error };
});
```

```js
producer.produce(<queueue>, <message>, { rpc: true })
.then((response) => {
   console.log(response);   // { error: {} }
});
```

**Comment by mrister** [comment]
Reprioritising by moving to backlog (higher).
