### ISSUE TITLE
Wrong json serialization of array in rpc

### ISSUE THREAD

**Issue by yosiat** [dial-once/node-bunnymq#97]
Hi,

I am using node-bunnymq to execute rpc request to service which expects to get messages as arrays.
For example:

```
bunnymq.publish('queue:name', [{ message: 'content' }], { rpc: true, timeout: 1000 })
```

I expect the rabbitmq payload to be: `[{"message":"content"}]`
But actually it's: `{"0":{"message":"content"}}`

This happens because of the `Object.assign` here - https://github.com/dial-once/node-bunnymq/blob/develop/src/modules/producer.js#L175

I'll try to make PR which removes that `Object.assign`, but why we do `Object.assign` here? I assume we want to duplicate the message, but there is no need since we are going to serialize it, no?

**Comment by mrister** [comment]
@yosiat Any contribution you can give is more than welcome, for more info about this you can see here https://github.com/dial-once/node-bunnymq/commit/35a01ee2d52cfff3f5f345e2e8206964a26b5fad

I suppose Object.assign was used here to do a shallow clone and thus not alter the incoming message argument.

**Comment by yosiat** [comment]
@mrister I can add special check for arrays or skip the shallow clone at all, wdyt?

**Comment by mrister** [comment]
A special check would indeed be better IMHO as we did for string and also adding your case as a test case. Minimizing the chance to unexpectedly alter an input argument is worth keeping.

**Comment by yosiat** [comment]
@mrister opened pr to fix the issue: https://github.com/dial-once/node-bunnymq/pull/98
let's move the discussion to their
